# Generated by Django 2.2.7 on 2019-11-27 14:38

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0002_auto_20191125_2202'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='information_users',
            new_name='InformationUsers',
        ),
        migrations.RenameField(
            model_name='informationusers',
            old_name='birth_date',
            new_name='briday_date',
        ),
    ]
